FROM golang:1.17 AS build
WORKDIR /go/src
COPY openapi ./openapi
COPY main.go .
COPY go.mod .

ENV CGO_ENABLED=0
RUN go get -d -v ./...

RUN go build -a -gcflags="all=-N -l" -installsuffix cgo -o openapi .

RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM scratch AS runtime
COPY --from=build /go/src/openapi ./
COPY --from=build /go/bin/dlv /
EXPOSE 8080/tcp 40000

CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/api-server"]

