/*
 * MassBank Tool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"encoding/json"
	"errors"
	"github.com/uly55e5/MassBankRepo/api-server/database"
	"github.com/uly55e5/MassBankRepo/api-server/massbank"
	"net/http"
	"os"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

func (s *DefaultApiService) UploadMassbankPost(ctx context.Context, filename string, file *os.File) (ImplResponse, error) {
	mb := massbank.Massbank{}
	mb.ParseFile(file.Name())
	id, err := database.InsertMassbank(mb)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}
	js, _ := json.Marshal(struct{ Id string }{id})
	return Response(http.StatusOK, string(js)), nil
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// GetAllSpectra -
func (s *DefaultApiService) GetAllSpectra(ctx context.Context, limit int64, offset int64, page int64) (ImplResponse, error) {
	// TODO - update GetAllSpectra with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []SpectrumListItem{}) or use other options such as http.Ok ...
	//return Response(200, []SpectrumListItem{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetAllSpectra method not implemented")
}

// GetAllSpectraInfo -
func (s *DefaultApiService) GetAllSpectraInfo(ctx context.Context, limit int64, offset int64, page int64) (ImplResponse, error) {
	// TODO - update GetAllSpectraInfo with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []SpectrumListItem{}) or use other options such as http.Ok ...
	//return Response(200, []SpectrumListItem{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetAllSpectraInfo method not implemented")
}

// GetSpectrum -
func (s *DefaultApiService) GetSpectrum(ctx context.Context, accession string) (ImplResponse, error) {
	// TODO - update GetSpectrum with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Spectrum{}) or use other options such as http.Ok ...
	//return Response(200, Spectrum{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSpectrum method not implemented")
}
