/*
 * MassBank Tool API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Spectrum struct {
	Accession string `json:"accession"`
}

// AssertSpectrumRequired checks if the required fields are not zero-ed
func AssertSpectrumRequired(obj Spectrum) error {
	elements := map[string]interface{}{
		"accession": obj.Accession,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseSpectrumRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Spectrum (e.g. [][]Spectrum), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSpectrumRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSpectrum, ok := obj.(Spectrum)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSpectrumRequired(aSpectrum)
	})
}
