services:
  mongo:
    ports:
      - "27017:27017"
  api-server:
    build:
      context: ../api-server/
      dockerfile: Dockerfile-debug
    ports:
      - 40000:40000
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "apparmor=unconfined"
    volumes:
      - ./log:/var/log
  meilisearch:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
  web-frontend:
    build:
      context: ../web-frontend
      dockerfile: Dockerfile-dev
    volumes:
      - ../web-frontend:/app
